#!/bin/bash
#
# Copyright 2014 (c)
# Gabriel-Andrew Pollo Guilbert
#
# This is a simple script that execute a specified
# project in this repository. I use it to escape Eclipse
# IDE because I use my own code editor.
#
# SYNTAX
#
# To run a single file:
#     ./run <PROJECT> <PACKAGE> <FILE>
#
# If the package is the same as the project:
#     ./run <PROJECT> - <FILE>
#
# To run a subproject with a makefile:
#     ./run <PROJECT> <PACKAGE> <MAKEFILE COMMAND>

DIR=$(pwd)
PROJECT=$1
PACKAGE=$2
OPTS=$3

# arg 1: file (-f) or directory (-d)
# arg 2: directory to search
# arg 3: type to list
function list {
	cd $2

	echo -e "\nPlease choose a $3 between these:"

	if [[ $1 == -d ]]; then
		for DIRECTORY in */ ; do
			echo -e "   **\t$DIRECTORY" | rev | cut -c 2- | rev
		done
	elif [[ $1 == -f ]]; then
		for FILE in *.java ; do
			echo -e "   **\t$FILE" | rev | cut -c 6- | rev
		done
	fi

	cd $DIR
}

# project related error checking
if [[ ! -n $PROJECT ]]; then
	echo "ERROR: No project specified."
	list -d ./ project
	exit 1
elif [[ ! -d $PROJECT ]]; then
	echo "ERROR: The specified project doesn't exist."
	list -d ./ project
	exit 1
fi

# package related error checking
if [[ ! -n $PACKAGE ]]; then
	echo "ERROR: No package specified."
	list -d ./$PROJECT/src/ project
	exit 1
elif [[ $PACKAGE == '-' ]]; then
	PACKAGE=$PROJECT
fi

if [[ ! -d $PROJECT/src/$PACKAGE ]]; then
	echo "ERROR: The specified package doesn't exist."
	list -d ./$PROJECT/src/ package
	exit 1
fi

# file related error checking and run them
if [[ -f $PROJECT/src/$PACKAGE/makefile ]]; then
	cd $PROJECT/src/$PACKAGE

	if [[ -n $3 ]]; then
		make $3
	else
		make && make run
	fi

	cd $DIR
elif [[ ! -n $OPTS ]]; then
	echo "ERROR: No file specified."
	list -f $PROJECT/src/$PACKAGE/ file
elif [[ -f $PROJECT/src/$PACKAGE/$OPTS.java ]]; then
	javac -encoding utf8 -verbose -deprecation ./$PROJECT/src/$PACKAGE/$OPTS.java
	java -cp ./$PROJECT/src/ $PACKAGE.$OPTS main
else
	echo "ERROR: The specified file doesn't exist."
	list -f $PROJECT/src/$PACKAGE/ file
fi

exit 0
